mystr ="sachin is a good boy"
# print(mystr[0:7])
# print(mystr[0:7:2])
# print(len(mystr))
# print(mystr[::-1])
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("boy"))
print(mystr.count("o"))
print(mystr.capitalize())
print(mystr.lower())
print(mystr.upper())
print(mystr.find("is"))
print(mystr.replace("is" , "are"))